package com.eliteonetube.glovebox.ui.viewmodels

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.eliteonetube.glovebox.data.GloveboxDatabase
import com.eliteonetube.glovebox.data.entity.FuelLog
import com.eliteonetube.glovebox.data.entity.Reminder
import com.eliteonetube.glovebox.data.entity.ServiceRecord
import com.eliteonetube.glovebox.data.entity.Vehicle
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import java.time.Instant
import java.time.YearMonth
import java.time.ZoneId
import java.util.concurrent.TimeUnit

data class EfficiencyPoint(val date: Long, val value: Double)
data class CategorySpending(val category: String, val amount: Double)
data class MonthlySpending(val month: String, val amount: Double)
data class MaintenancePrediction(
    val description: String,
    val targetMileage: Int,
    val predictedDate: Long,
    val daysRemaining: Long,
    val isAutoGenerated: Boolean = false,
    val descriptionResId: Int? = null
)

data class InsightsState(
    val efficiencyHistory: List<EfficiencyPoint> = emptyList(),
    val spendingByCategory: List<CategorySpending> = emptyList(),
    val monthlySpending: List<MonthlySpending> = emptyList(),
    val predictions: List<MaintenancePrediction> = emptyList(),
    val totalCost: Double = 0.0,
    val averageEfficiency: Double = 0.0,
    val odometerUnit: String = "km",
    val preferredCurrency: String = "USD"
)

@OptIn(ExperimentalCoroutinesApi::class)
class InsightsViewModel(application: Application, initialVehicleId: Long) : AndroidViewModel(application) {
    private val db = GloveboxDatabase.getDatabase(application)
    private val fuelLogDao = db.fuelLogDao()
    private val serviceRecordDao = db.serviceRecordDao()
    private val vehicleDao = db.vehicleDao()
    private val reminderDao = db.reminderDao()
    private val userPrefs = com.eliteonetube.glovebox.data.UserPreferencesRepository(application)

    private val _selectedVehicleId = MutableStateFlow(initialVehicleId)
    val selectedVehicleId: StateFlow<Long> = _selectedVehicleId.asStateFlow()

    val vehicles: StateFlow<List<Vehicle>> = vehicleDao.getAllVehicles()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    val selectedVehicle: StateFlow<Vehicle?> = _selectedVehicleId.flatMapLatest { id ->
        if (id == 0L) flowOf<Vehicle?>(null)
        else flow { emit(vehicleDao.getVehicleById(id)) }
    }.stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), null)

    val uiState: StateFlow<InsightsState> = combine(
        _selectedVehicleId,
        userPrefs.preferredCurrency
    ) { id, preferredCurrency ->
        id to preferredCurrency
    }.flatMapLatest { (id, preferredCurrency) ->
        val fuelsFlow = if (id == 0L) fuelLogDao.getAllFuelLogs() else fuelLogDao.getFuelLogsForVehicle(id)
        val servicesFlow = if (id == 0L) serviceRecordDao.getAllServiceRecords() else serviceRecordDao.getServiceRecordsForVehicle(id)
        val remindersFlow = if (id == 0L) reminderDao.getAllReminders() else reminderDao.getRemindersForVehicle(id)
        val vehicleFlow: Flow<Vehicle?> = if (id == 0L) flowOf(null) else flow { emit(vehicleDao.getVehicleById(id)) }

        combine(fuelsFlow, servicesFlow, remindersFlow, vehicleFlow) { fuels, services, reminders, vehicle ->
            calculateInsights(fuels, services, reminders, vehicle, preferredCurrency)
        }
    }.stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), InsightsState())

    fun selectVehicle(id: Long) {
        _selectedVehicleId.value = id
    }

    private fun calculateInsights(
        fuels: List<FuelLog>, 
        services: List<ServiceRecord>,
        reminders: List<Reminder>,
        vehicle: Vehicle?,
        preferredCurrency: String
    ): InsightsState {
        if (fuels.isEmpty() && services.isEmpty()) return InsightsState(preferredCurrency = preferredCurrency)

        val unit = vehicle?.odometerUnit ?: "km"
        val converter = com.eliteonetube.glovebox.util.CurrencyUtility

        // 1. Efficiency History (L/100km or MPG)
        val efficiencyPoints = mutableListOf<EfficiencyPoint>()
        val fuelsByVehicle = fuels.groupBy { it.vehicleId }
        
        fuelsByVehicle.forEach { (vId, vehicleFuels) ->
            val vUnit = if (vId == vehicle?.id) vehicle.odometerUnit else "km"
            
            val sortedFuels = vehicleFuels.sortedBy { it.date }
            for (i in 0 until sortedFuels.size - 1) {
                val current = sortedFuels[i]
                val next = sortedFuels[i + 1]
                val distance = next.odometer - current.odometer
                if (distance > 0) {
                    val efficiency = if (vUnit == "mi") {
                        distance.toDouble() / next.amount
                    } else {
                        (next.amount / distance) * 100
                    }
                    efficiencyPoints.add(EfficiencyPoint(next.date, efficiency))
                }
            }
        }
        efficiencyPoints.sortBy { it.date }

        // 2. Spending by Category (Converted to Preferred Currency)
        val fuelTotal = fuels.sumOf { converter.convert(it.totalCost, it.currency, preferredCurrency) }
        val serviceTotal = services.sumOf { converter.convert(it.cost ?: 0.0, it.currency, preferredCurrency) }
        
        val categorySpending = listOf(
            CategorySpending("Fuel", fuelTotal),
            CategorySpending("Service", serviceTotal)
        ).filter { it.amount > 0 }

        // 3. Monthly Spending (Converted to Preferred Currency)
        val allCosts = mutableListOf<Pair<Long, Double>>()
        fuels.forEach { allCosts.add(it.date to converter.convert(it.totalCost, it.currency, preferredCurrency)) }
        services.forEach { allCosts.add(it.date to converter.convert(it.cost ?: 0.0, it.currency, preferredCurrency)) }

        val monthlyMap = mutableMapOf<YearMonth, Double>()
        allCosts.forEach { (date, cost) ->
            val month = YearMonth.from(Instant.ofEpochMilli(date).atZone(ZoneId.systemDefault()))
            monthlyMap[month] = monthlyMap.getOrDefault(month, 0.0) + cost
        }
        
        val monthlySpending = monthlyMap.entries
            .sortedBy { it.key }
            .takeLast(6)
            .map { MonthlySpending(it.key.month.name.take(3), it.value) }

        // 4. Smart Maintenance Predictions
        val predictions = mutableListOf<MaintenancePrediction>()
        if (vehicle != null) {
            val allOdoLogs = (fuels.filter { it.vehicleId == vehicle.id }.map { it.date to it.odometer } + 
                             services.filter { it.vehicleId == vehicle.id }.map { it.date to it.mileage })
                .sortedBy { it.first }
            
            if (allOdoLogs.size >= 2) {
                val first = allOdoLogs.first()
                val last = allOdoLogs.last()
                val totalDist = last.second - first.second
                val totalDays = TimeUnit.MILLISECONDS.toDays(last.first - first.first)
                
                if (totalDist > 0 && totalDays > 0) {
                    val avgDailyDist = totalDist.toDouble() / totalDays
                    
                    // Manual reminders first
                    val manualDescriptions = reminders.filter { it.vehicleId == vehicle.id && !it.isCompleted }
                        .map { it.description.lowercase() }

                    reminders.filter { it.vehicleId == vehicle.id && !it.isCompleted && it.targetMileage != null }.forEach { reminder ->
                        val target = reminder.targetMileage!!
                        if (target > vehicle.odometer) {
                            val distRemaining = target - vehicle.odometer
                            val daysToTarget = (distRemaining / avgDailyDist).toLong()
                            val predictedDate = System.currentTimeMillis() + TimeUnit.DAYS.toMillis(daysToTarget)
                            
                            predictions.add(MaintenancePrediction(
                                description = reminder.description,
                                targetMileage = target,
                                predictedDate = predictedDate,
                                daysRemaining = daysToTarget
                            ))
                        }
                    }

                    // Smart Auto-Predictions (Universal Intervals)
                    val standardServices = listOf(
                        com.eliteonetube.glovebox.R.string.oil_change to if (unit == "mi") 5000 else 8000,
                        com.eliteonetube.glovebox.R.string.brake_service to if (unit == "mi") 40000 else 65000,
                        com.eliteonetube.glovebox.R.string.tire_rotation to if (unit == "mi") 6000 else 10000,
                        com.eliteonetube.glovebox.R.string.air_filter to if (unit == "mi") 20000 else 30000
                    )

                    standardServices.forEach { (resId, interval) ->
                        // Simplified check - might need more robust matching if names vary
                        val name = getApplication<Application>().getString(resId)
                        if (manualDescriptions.none { it.contains(name.lowercase()) }) {
                            val lastService = services.filter { it.vehicleId == vehicle.id && it.serviceType.lowercase().contains(name.lowercase()) }
                                .maxByOrNull { it.date }
                            
                            val lastMileage = lastService?.mileage ?: 0
                            var nextTarget = ((vehicle.odometer / interval) + 1) * interval
                            
                            // If we have a record of when it was last done, be more precise
                            if (lastService != null) {
                                nextTarget = lastMileage + interval
                            }

                            if (nextTarget > vehicle.odometer) {
                                val distRemaining = nextTarget - vehicle.odometer
                                val daysToTarget = (distRemaining / avgDailyDist).toLong()
                                val predictedDate = System.currentTimeMillis() + TimeUnit.DAYS.toMillis(daysToTarget)
                                
                                predictions.add(MaintenancePrediction(
                                    description = name,
                                    targetMileage = nextTarget,
                                    predictedDate = predictedDate,
                                    daysRemaining = daysToTarget,
                                    isAutoGenerated = true,
                                    descriptionResId = resId
                                ))
                            }
                        }
                    }
                }
            }
        }
        predictions.sortBy { it.daysRemaining }

        return InsightsState(
            efficiencyHistory = efficiencyPoints,
            spendingByCategory = categorySpending,
            monthlySpending = monthlySpending,
            predictions = predictions,
            totalCost = fuelTotal + serviceTotal,
            averageEfficiency = if (efficiencyPoints.isNotEmpty()) efficiencyPoints.map { it.value }.average() else 0.0,
            odometerUnit = unit,
            preferredCurrency = preferredCurrency
        )
    }
}
